# Generated by Django 4.0.2 on 2022-02-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_body_homecaruselmodel_body_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecaruselmodel',
            old_name='body_en',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='homecaruselmodel',
            old_name='summary_en',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='homecaruselmodel',
            old_name='title_en',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='body_en',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='summary_en',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='summary_ru',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='homecaruselmodel',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='homecaruselmodel',
            name='body_uz',
        ),
        migrations.RemoveField(
            model_name='homecaruselmodel',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='homecaruselmodel',
            name='summary_uz',
        ),
        migrations.RemoveField(
            model_name='homecaruselmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='homecaruselmodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='body_uz',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='summary_uz',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='title_uz',
        ),
    ]
