# Generated by Django 4.0.2 on 2022-02-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220222_1236'),
        ('articles', '0003_rename_body_en_homecaruselmodel_body_and_more'),
    ]

    operations = [
    ]
